### PR TITLE
implemented blocking users

### PR DESCRIPTION
**Pull request by jimxj**

### CODE REVIEW

**Comment by jimxj** [comment]
@priteshshah1983 and @vincentwlau please review.

I added some test cases in MMXUserPreferencesTest and they passed in http://ms-jenkinsslave-01.magnet.com:8080/view/Android%20SDK/job/MMX-Android-Jim/4/.

**Comment by priteshshah1983** [comment]
Are `UserBlockingTask`s serially executed?

**Comment by jimxj** [comment]
UserBlockingTask is running in a background thread.

**Comment by jimxj** [comment]
I added a lock to make sure the add/remove users is atomic : https://github.com/magnetsystems/message-sdk-java-android/commit/7a6d1d09e4117821d6e89f6d95d3d5c45ce4a716

**Comment by jimxj** [comment]
@pekboy @tn052002 , for the usage of API, I have a unit test case for it : android/src/androidTest/java/com/magnet/mmx/client/api/MMXUserPreferencesTest.java

**Pull request merged**
